name: Build Lunar IDE for Windows(x86_64)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    name: Build for Windows (x86_64)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          cache: ''

      - name: Build Windows x86_64
        run: |
          pip install customtkinter pyinstaller
          python -m PyInstaller lunaridle_project/build/lunar_idle.spec --distpath dist --workpath build

      - name: Organize Artifacts
        shell: pwsh
        run: |
          $targetDir = "lunaridle_project/workflow/windows"
          New-Item -ItemType Directory -Force -Path $targetDir
          
          Write-Host "Conteúdo da pasta dist:"
          Get-ChildItem -Path "dist"

          if (Test-Path "dist/lunar_idle.exe") {
            Copy-Item -Path "dist/lunar_idle.exe" -Destination "$targetDir/lunar_idle_x86_64.exe" -Force
            Write-Host "Copiado com sucesso para $targetDir/lunar_idle_x86_64.exe"
            Get-ChildItem -Path $targetDir
          } else {
            Write-Error "Erro crítico: dist/lunar_idle.exe não foi encontrado."
            exit 1
          }

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lunar-ide-windows-x86_64
          path: lunaridle_project/workflow/windows/
